### list health
GET http://localhost:3000/health HTTP/1.1

#### get repo details
GET http://localhost:3000/repos/damarshah/githubAnalytics HTTP/1.1

#### get repo languages
GET http://localhost:3000/repos/Kubernetes/Kubernetes/contributors HTTP/1.1

### test
GET http://localhost:3000/repos/TEST-ROUTE